name: Node.js CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node-tests:
    name: Node.js Tests on ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [amd64, s390x]
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup QEMU (for s390x)
        if: matrix.platform == 's390x'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: s390x

      - name: Run Node.js tests on ${{ matrix.platform }}
        run: |
          if [ "${{ matrix.platform }}" = "s390x" ]; then
            echo "Running Node.js tests on s390x platform..."
            docker run --rm --platform linux/s390x node:${{ matrix.node-version }} bash -c "
              apt-get update && apt-get install -y python3 php-cli && \
              npm install && \
              npm run test:e2e && \
              npm run test:unit
            "
          else
            echo "Running Node.js tests on amd64 platform..."
            sudo apt-get update && sudo apt-get install -y python3 php-cli
            npm install
            npm run test:e2e
            npm run test:unit
          fi

  bun-tests:
    name: Bun Tests on ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [amd64, s390x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup QEMU (for s390x)
        if: matrix.platform == 's390x'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: s390x

      - name: Remove Node.js (if any)
        run: |
          if command -v node &> /dev/null; then sudo rm -rf "$(which node)"; fi
          if command -v npm &> /dev/null; then sudo rm -rf "$(which npm)"; fi

      - name: Run Bun tests on ${{ matrix.platform }}
        run: |
          if [ "${{ matrix.platform }}" = "s390x" ]; then
            echo "Running Bun tests on s390x platform..."
            docker run --rm --platform linux/s390x ubuntu:22.04 bash -c "
              apt-get update && apt-get install -y curl python3 php-cli wget tar xz-utils tzdata && \
              ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime && dpkg-reconfigure --frontend noninteractive tzdata && \
              curl -fsSL https://bun.sh/install | bash && \
              export BUN_INSTALL=/root/.bun && export PATH=\$BUN_INSTALL/bin:\$PATH && \
              bun install && \
              bun run test:e2e && \
              bun run test:unit
            "
          else
            echo "Running Bun tests on amd64 platform..."
            # native amd64 runner
            sudo apt-get update && sudo apt-get install -y python3 php-cli
            curl -fsSL https://bun.sh/install | bash
            export BUN_INSTALL=$HOME/.bun
            export PATH=$BUN_INSTALL/bin:$PATH
            bun install
            bun run test:e2e
            bun run test:unit
          fi

